## Numpy Learning

In [10]:
import numpy as np


*Numpy Array Creation* 


Function | Description
np.array() | From list or tuple
np.zeros() | All zeros
np.ones() | All ones
np.full() | All a specific value
np.eye() | Identity matrix
np.arange() | Range with step (like range())
np.linspace() | Evenly spaced values between limits
np.random.rand() | Random floats (0–1)
np.random.randint() | Random integers
np.empty() | Uninitialized array

In [ ]:
#You can create an array directly from lists or tuples.
arr1 = np.array([1, 2, 3])              # 1D array
arr2 = np.array([[1, 2], [3, 4]])            # 2D array
arr2

# np.asarray() – convert list/tuple to array (faster than np.array)

array([[1, 2],
       [3, 4]])

In [15]:
#np.zeros() → Array of all zeros
np.zeros((2, 3))  # shape: 2 rows, 3 columns


array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#np.ones() → Array of all ones
np.ones((3, 2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
#np.full() → Array filled with a specific value
np.full((2, 2), 99)  # 2x2 array filled with 7


array([[99, 99],
       [99, 99]])

In [36]:
#np.eye() → Identity matrix
np.eye(2)  # 3x3 identity matrix


array([[1., 0.],
       [0., 1.]])

In [22]:
#np.arange(start, stop, step)
np.arange(0, 10, 4)  # [0 2 4 6 8]


array([0, 4, 8])

In [23]:
#np.linspace(start, stop, num)
#Returns evenly spaced numbers including endpoints

np.linspace(0, 1, 5)  # [0.  0.25  0.5  0.75  1.]



array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
#np.random.rand() → Uniform between 0 and 1
np.random.rand(2, 3)  # 2x3 array


array([[0.14725283, 0.74702023, 0.30291673],
       [0.23930086, 0.76504576, 0.34889979]])

In [25]:
#np.random.randint() → Random integers in a range
np.random.randint(1, 10, (2, 2))  # 2x2 integers from 1 to 9


array([[6, 9],
       [5, 2]], dtype=int32)

In [28]:
#np.random.randn() → Standard normal distribution
np.random.randn(3, 3)



array([[ 4.95311619e-01, -3.68265233e-01, -4.81168653e-01],
       [ 6.80336436e-01, -2.94337896e-01,  1.88198978e+00],
       [ 7.99238359e-01, -4.76739248e-04, -8.25208216e-01]])

In [30]:
#5. Empty or Uninitialized Arrays
#(Not often used unless you’re filling them later)
np.empty((2, 3))  # Values are garbage until set


array([[0.14725283, 0.74702023, 0.30291673],
       [0.23930086, 0.76504576, 0.34889979]])

In [35]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [40]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#np.copy() – deep copy of an array
arr2=np.copy(arr)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

*N-D arrays properties and attributes*

* arr = np.array([[1, 2, 3],[4, 5, 6]])
* Dimensions (ndim) arr.ndim
#Output: 2 → it's a 2D array 
* Shape (rows, cols) arr.shape
#Output: (2, 3) → 2 rows, 3 columns
* Total Elements arr.size
#Output: 6 → total number of values
* Data Type of Each Element arr.dtype
#Output: dtype('int64') → 64-bit integers
*  Size of One Item (in bytes) arr.itemsize
#Output: 8 → each int64 takes 8 bytes
* Transpose (Flip rows and columns) arr.T
#Output:
#array([[1, 4],
#[2, 5],
#[3, 6]])






*N-D arrays Methods*

*  "SHAPE AND STRUCTURE"	            
* arr.reshape()	Reshapes array without changing data
* arr.flatten()	Converts to 1D array
* arr.transpose() or arr.T	Transposes array (rows <-> cols)
* arr.ravel()	Flattens like flatten() but returns view
* "MATH OPERATION"
* arr.sum()	Sum of all elements
* arr.mean()	Mean value
* arr.std()	Standard deviation
* arr.min()	Minimum value  axis=0 for column wise min and max,axis=1 for same eg arr.min(axis=0)
* arr.max()	Maximum value eg arr.max(axis=1) fro rowise max
* np.median(arr) for median of arr,can use axis=0
* np.sin(arr) for sin of values
* np.exp(arr)  mean e^values each
* np.sqrt(arr) each value
* np.square(arr) each value
* arr.argmin()	Index of minimum value
* arr.argmax()	Index of maximum value
* "SORTING AND SEARCHING"
* arr.sort()	Sorts array (in-place or copy)
* np.sort(arr)	Returns sorted array
* arr.argsort()	Returns indices to sort the array
* np.where()	Returns indices where condition is true
* "COPYING AND MODIFYING"
* arr.copy()	Returns a copy of the array
* arr.astype()	Converts array to different data type
* arr.fill(value)	Fills array with single value
* "LOGICAL AND BOOLEAN"
* arr.any()	True if any element is True
 * arr.all()	True if all elements are True


In [63]:
#Array Comparison
a = np.array([1, 2, 3])
b = np.array([1, 2, 4])
a == b         # [True, True, False]
a != b         # [False, False, True]


array([False, False,  True])

In [89]:
#Aggregation by Axis
arr = np.array([[1, 2], [3, 4]])
arr.sum(axis=0)   # [4, 6] → column-wise sum
arr.sum(axis=1) 
# [3, 7] → row-wise sum


array([3, 7])

*indexing slicing and iteration*

In [104]:
# Indexing (Just like lists, but more powerful!)
#For 1D Arrays:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])     # 10
print(arr[-1])    # 50
#2D arrays
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr[0, 1])   # Row 0, Col 1 → 2
print(arr[1][2])   # Row 1, Col 2 → 6


10
50
2
6


In [105]:
# Slicing
#1D Slicing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])    # [20 30 40]
print(arr[::-1])   # [50 40 30 20 10]
#2D Slicing
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[0:2, 1:])   # Rows 0-1, Cols 1-end → [[2 3], [5 6]]
print(arr[:, 0])      # All rows, column 0 → [1 4 7]
#: → means entire range (like all),Negative indices work (-1 is last row/column)


[20 30 40]
[50 40 30 20 10]
[[2 3]
 [5 6]]
[1 4 7]


In [110]:
 # Iteration
 # 2D Iteration:
arr = np.array([[1, 2], [3, 4]])
for row in arr:
    print("Row:", row)

# Iterating over each element
for x in np.nditer(arr):
    print("Element:", x)
    
    #Bonus: Loop with index
for index, val in np.ndenumerate(arr):
  print(f"Index {index} has value {val}")



Row: [1 2]
Row: [3 4]
Element: 1
Element: 2
Element: 3
Element: 4
Index (0, 0) has value 1
Index (0, 1) has value 2
Index (1, 0) has value 3
Index (1, 1) has value 4


In [ ]:
np.vstack() – vertical stack (row-wise)
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v = np.vstack((a, b))

print(v)
#Output:
#[[1 2 3]
#[4 5 6]]
#Shape: (2, 3)
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])

np.vstack((a, b))  # Shape: (2, 3)

np.hstack() – horizontal stack (column-wise)
#All arrays must have the same number of rows (axis=0 must match).
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

h = np.hstack((a, b))

print(h)
#Output:
#[[1 4]
#[2 5]
#[3 6]]
#Shape: (3, 2)

vstack()	Vertical (adds rows)	Number of columns (axis=1)
hstack()	Horizontal (adds columns)	Number of rows (axis=0)




*Splitting*

np.vsplit() — Vertical Split (row-wise)
Rule:
#You must split along rows.

The #number of rows must be divisible by the number of splits.
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

#Split into 2 vertical parts (2 sub-arrays, each with 2 rows)
v = np.vsplit(a, 2)

for part in v:
    print(part)
#If the number of rows (4 in this case) wasn't divisible by 2, it would raise an error.

np.hsplit() — Horizontal Split (column-wise)
#You must split along columns.

#The number of columns must be divisible by the number of splits.
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

#Split into 2 horizontal parts (2 columns in each split)
h = np.hsplit(a, 2)

for part in h:
    print(part)
    
    Function	    Splits Along	    Must Divide Evenly
    vsplit()	    Rows (axis=0)	    Number of rows
    hsplit()	    Columns (axis=1)	Number of columns
    
 You can also split at specific indices using:

 
np.vsplit(a, [1, 3])  # custom row split
np.hsplit(a, [1, 3])  # custom column split



In [ ]:
#*Fancy Indexing*
arr=np.arange(24).reshape(6,4)
arr[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [150]:
#INDEXING WITH BOOLEAN ARRAYS
arr[arr>10]
arr[(arr>10) & (arr%2==0)]
arr[(arr>10) & (arr%2==0)]=0
arr
 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0, 13,  0, 15],
       [ 0, 17,  0, 19],
       [ 0, 21,  0, 23]])

*Stacking in NumPy*  

*Broadcasting*  
* Broadcasting lets NumPy perform arithmetic operations on arrays of different shapes without writing loops
* It's a shortcut that "stretches" smaller arrays to match larger ones — behind the scenes.
 * it is more intutive , no need to learn the rules
 

In [171]:
np.random.uniform(1,100,10).reshape(2,5)

array([[98.11116484,  6.93425689, 89.16404853, 58.11324844, 74.50548922],
       [63.38820971, 58.60237705,  3.02347407, 21.79263119, 54.92380294]])

In [175]:
np.random.randint(1,10,5)

array([4, 1, 5, 5, 6], dtype=int32)